# Lab 6: Introduction to NumPy

Welcome to your first NumPy lab.

To begin, create a copy of this file using File -> Save as... and name the new file "Lab_6_LastName_FirstName.ipynb" using your last and first name.  Make sure to execute all the code cells in the notebook and that the outputs show in your report. *Two points are allocated for reading and running the code blocks*. Before submitting, remember to add a collaboration statement in this mark down indicating the contribution of each member. You may edit the template below:

- Group member 1 first name, last name & student id: contributions here
- Group member 2 first name, last name & student id: contributions here
- if applicable, Group member 3 first name, last name & student id: contributions here


Up to this point, you have been working with core Python tools such as:
- variables
- lists
- indexing
- loops
- conditionals
- functions

Those tools are still important. NumPy does **not** replace Python. Instead, it gives us a better tool for working with **numerical data**.

In this lab, you will learn how NumPy helps us store and work with numbers more efficiently than regular Python lists when we are doing math, science, engineering, or data-focused tasks.

---

## What is NumPy?

**NumPy** stands for **Numerical Python**.

It is a Python library that gives us a special data type called an **array**. A NumPy array is similar to a Python list, but it is designed specifically for numbers and numerical operations.

That means NumPy makes it easier to:
- store many values together
- perform math on all values at once
- organize data into rows and columns
- prepare for future work in data science, engineering, biology, healthcare, and machine learning

---

## How does NumPy build from what we already know?

You already know how to make a Python list like this:

```python
heart_rates = [72, 88, 95, 67, 81]
```

A NumPy array looks very similar:

```python
heart_rates = np.array([72, 88, 95, 67, 81])
```

So the idea is familiar:
- both store multiple values
- both use square brackets
- both can be indexed

But NumPy arrays are much stronger for number-based work because they support fast, clean **element-wise math**.

For example, with NumPy you can add 5 to every value in the array with one line of code.

---

## Why are we learning this?

NumPy is one of the most commonly used Python libraries in technical fields.

If you continue in:
- engineering
- biology
- bioengineering
- chemistry
- healthcare
- data analysis
- machine learning

you will almost certainly see NumPy again.

Think of this lab as your first step from "basic Python programming" into "Python for real scientific and technical data."

---

## What you will learn in this lab

By the end of this lab, you should be able to:
1. import NumPy
2. create 1D and 2D arrays
3. inspect array properties
4. access values using indexing
5. perform element-wise math
6. use basic NumPy functions like `sum()`, `mean()`, `max()`, and `min()`

---
## Important Note

In many environments, NumPy is already installed.

Examples:
- Google Colab
- Anaconda
- some Jupyter Notebook installations

If `import numpy as np` works without an error, then you do **not** need to install anything.

---

## The Most Reliable Install Command

If you need to install NumPy, open your terminal and use:

```python
python -m pip install numpy
```

On some Windows systems, this version works better:

```python
py -m pip install numpy
```

On many Mac systems, use:

```python
python3 -m pip install numpy

```

### If you are using Google Colab
NumPy is usually already installed.

---

## Importing NumPy

By convention, we usually import NumPy using the alias `np`.

That looks like this:

```python
import numpy as np
```

This saves typing and is the standard style you will see in tutorials and real code.

---



# Using NumPy Examples
## Step 1: Import NumPy

Before we can use NumPy, we need to import it.
Run the cell below.


In [1]:
import numpy as np

## Step 2: Creating a 1D NumPy Array

A **1D array** is like a single row of values.

This is similar to a Python list, but created with `np.array()`.

### Example


In [2]:
heart_rates = np.array([72, 88, 95, 67, 81])
print(heart_rates)



[72 88 95 67 81]


### What happened?

We created a NumPy array named `heart_rates`.

Notice the pattern:
- `np.array(...)` creates the array
- the values go inside square brackets
- the result prints a sequence of numbers

This should feel similar to a Python list, which is good. NumPy is building on something you already know.


## Step 3: Python List vs NumPy Array

Let's compare them directly.


In [3]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print("Python list:", python_list)
print("NumPy array:", numpy_array)

Python list: [1, 2, 3]
NumPy array: [1 2 3]


At first glance, these look similar.

But the real difference appears when we do math.


In [4]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print("Python list * 2 =", python_list * 2)
print("NumPy array * 2 =", numpy_array * 2)

Python list * 2 = [1, 2, 3, 1, 2, 3]
NumPy array * 2 = [2 4 6]


### Important idea

A Python list repeated by 2 gives:

```python
[1, 2, 3, 1, 2, 3]
```

A NumPy array multiplied by 2 gives:

```python
[2 4 6]
```

That is because NumPy applies the math to **each value** in the array.

This is called **element-wise operation**.


## Step 4: Inspecting Array Information

NumPy arrays have useful properties that help us understand the data.


In [5]:
heart_rates = np.array([72, 88, 95, 67, 81])

print("Array:", heart_rates)
print("Shape:", heart_rates.shape)
print("Number of dimensions:", heart_rates.ndim)
print("Size:", heart_rates.size)
print("Data type:", heart_rates.dtype)

Array: [72 88 95 67 81]
Shape: (5,)
Number of dimensions: 1
Size: 5
Data type: int64


### Vocabulary

- `shape` tells us the structure of the array
- `ndim` tells us how many dimensions it has
- `size` tells us the total number of values
- `dtype` tells us the kind of data stored inside

For a simple 1D array of 5 values, the shape will look like `(5,)`.


## Step 5: Indexing a NumPy Array

Just like Python lists, NumPy arrays use indexing.

Remember:
- index `0` is the first value
- index `1` is the second value
- index `-1` is the last value


In [6]:
heart_rates = np.array([72, 88, 95, 67, 81])

print("First value:", heart_rates[0])
print("Third value:", heart_rates[2])
print("Last value:", heart_rates[-1])

First value: 72
Third value: 95
Last value: 81


## Step 6: Element-Wise Math

This is one of the biggest reasons NumPy is so useful.

You can perform math across the whole array at once.


In [7]:
heart_rates = np.array([72, 88, 95, 67, 81])

print("Add 5:", heart_rates + 5)
print("Multiply by 2:", heart_rates * 2)
print("Subtract 10:", heart_rates - 10)

Add 5: [ 77  93 100  72  86]
Multiply by 2: [144 176 190 134 162]
Subtract 10: [62 78 85 57 71]


Each operation is applied to every value in the array.

This saves time and makes code cleaner.


## Step 7: Common NumPy Functions

NumPy also includes built-in functions for common numerical summaries.


In [8]:
heart_rates = np.array([72, 88, 95, 67, 81])

print("Sum:", np.sum(heart_rates))
print("Mean:", np.mean(heart_rates))
print("Max:", np.max(heart_rates))
print("Min:", np.min(heart_rates))

Sum: 403
Mean: 80.6
Max: 95
Min: 67


These functions are especially useful when working with measurements, scores, sensor readings, lab data, or patient data.


## Step 8: Creating a 2D Array

A **2D array** is like a table with rows and columns.

This is useful for storing grouped data.
For example, each row could represent a patient, and each column could represent a measurement.


In [13]:
patient_data = np.array([
    [72, 98.6, 120],
    [88, 99.1, 135],
    [95, 100.2, 140]
])

print(patient_data)

[[ 72.   98.6 120. ]
 [ 88.   99.1 135. ]
 [ 95.  100.2 140. ]]


### Thinking about the table

You can imagine this as:

- row 0 -> first patient
- row 1 -> second patient
- row 2 -> third patient

and:

- column 0 -> heart rate
- column 1 -> temperature
- column 2 -> systolic pressure


In [14]:
print("Shape:", patient_data.shape)
print("Dimensions:", patient_data.ndim)

Shape: (3, 3)
Dimensions: 2


A shape of `(3, 3)` means:
- 3 rows
- 3 columns


## Step 9: Indexing a 2D Array

For a 2D array, indexing uses:

```python
array_name[row, column]
```

The first number is the row.
The second number is the column.


In [15]:
print(patient_data[0, 0])   # first row, first column
print(patient_data[1, 1])   # second row, second column
print(patient_data[2, 2])   # third row, third column

72.0
99.1
140.0


## Step 10: Simple Slicing

Slicing lets us grab part of an array.

For a 1D array:


In [17]:
heart_rates = np.array([72, 88, 95, 67, 81])
print(heart_rates[1:4])

[88 95 67]


For a 2D array:
- `:` means all rows or all columns in that position


In [18]:
print("First row:", patient_data[0, :])
print("First column:", patient_data[:, 0])

First row: [ 72.   98.6 120. ]
First column: [72. 88. 95.]


# Student Exercises

Complete the exercises below in the empty code cells.

Put your answers directly under each exercise.

**Total: 10 points**

## Submission Reminder

Before you submit:
- make sure every code cell has been run
- make sure your output is visible
- double-check spelling in variable names
- make sure you used `import numpy as np`

If NumPy gives an error that it is not installed, review the installation section at the top of the notebook.


## Exercise 0 (1 pt)

Create a NumPy array called `temperatures` with these values:

`98.6, 99.1, 100.2, 97.9, 98.4`

Then print the array.

Using your `temperatures` array, print:
1. the shape
2. the number of dimensions
3. the size



In [ ]:
# Exercise 1
temps = np.array([98.6, 99.1, 100.2, 97.9, 98.4])
print("Shape: ", temps.shape)
print("Number of Dimensions: ", temps.ndim)
print("Size: ", temps.size)


Shape:  (5,)
Number of Dimensions:  1
Size:  5


## Exercise 1 (0.5 pt)

Using the `temperatures` array, print:
1. the first value
2. the third value
3. the last value


In [10]:
# Exercise 3
print("First value: ", temps[0])
print("Third value: ", temps[2])
print("Last value: ", temps[-1])




First value:  98.6
Third value:  100.2
Last value:  98.4


## Exercise 2 (0.5 pts)

Create a NumPy array called `steps` with these values:

`3500, 4200, 5100, 6800, 7500`

Then print:
1. `steps + 500`
2. `steps * 2`


In [7]:
# Exercise 3
steps = np.array([2500, 4200, 5100, 6800, 7500])
print("Steps + 500: ", steps + 500)
print("Steps * 2: ", steps*2)


Steps + 500:  [3000 4700 5600 7300 8000]
Steps * 2:  [ 5000  8400 10200 13600 15000]


## Exercise 3 (2 pts)

Create a 2D NumPy array called `lab_results` using this data:

```python
[
    [4.5, 140, 98],
    [3.8, 135, 102],
    [4.1, 142, 95]
]
```

Then print:
1. the whole array
2. its shape
3. the value in row 1, column 2
4. the value in row 3, column 1

Note: In Python indexing, row 1 means index 0, row 3 means index 2, and so on.


In [11]:
# Exercise 6
lab_results = np.array([
    [4.5, 140, 98],
    [3.8, 135, 102],
    [4.1, 142, 95]
])

print("Lab results: ", lab_results)
print("Shape: ", lab_results.shape)
print("Lab results row 1 column 2: ", lab_results[0,1])
print("Lab results row 3 column 1: ", lab_results[2,0])

Lab results:  [[  4.5 140.   98. ]
 [  3.8 135.  102. ]
 [  4.1 142.   95. ]]
Shape:  (3, 3)
Lab results row 1 column 2:  140.0
Lab results row 3 column 1:  4.1


# Data Analysis Exercises
Background: Diffusion and Fick's Law

In biotransport, molecules often move across membranes through **diffusion**.

One way to estimate the diffusion rate is using **Fick's Law**:

$
J = -D \frac{dC}{dx}
$

where:

- **J** = diffusion flux (mol/m²·s)
- **D** = diffusion coefficient (m²/s)
- **dC/dx** = concentration gradient across the membrane


## Experimental Data

Distance across membrane (meters):

0.0, 0.002, 0.004, 0.006, 0.008

Measured oxygen concentration (mol/m³):

0.90, 0.75, 0.62, 0.51, 0.40

In [24]:
import numpy as np

distance = [0.0, 0.002, 0.004, 0.006, 0.008]
concentration = [0.90, 0.75, 0.62, 0.51, 0.40]

D = 2.1e-9



# Exercise 4: Diffusion Flux Calculation (3 pts)

Convert the lists to NumPy arrays and calculate the diffusion flux across the membrane.

### Part A (1 pt)
Convert `distance` and `concentration` into **NumPy arrays**.

### Part B (1 pt)
Calculate the **concentration gradient** using:


$dC/dx = \frac{C_{last} - C_{first}}{x_{last} - x_{first}}$

Print the gradient.

### Part C (1 pt)
Using **Fick's Law**, calculate the diffusion flux:

$J = -D \frac{dC}{dx}$

Print the flux value.

In [31]:
# Part A
d = np.array(distance)
c = np.array(concentration)

# Part B
conc_gradient = (c[-1] - c[0]) / (d[-1] - d[0])

# Part C
flux = -D*conc_gradient
print(flux)



1.3125000000000001e-07


# Exercise 5: Gradient Analysis with NumPy (3 pts)

In real experiments we often want to estimate the gradient **at every measurement point**, not just across the entire membrane.

NumPy includes a function called:

```python
np.gradient()
```

This function calculates the rate of change between data points.

### Part A (1 pt)
Convert `distance` and `concentration` into **NumPy arrays**.

### Part B (1 pt)
Use:

```python
np.gradient(concentration, distance)
```

to calculate the **local concentration gradient** across the membrane.

Print the result.

### Part C (1 pt)
Using the gradient values and Fick's Law, calculate the **flux at every point**.

Print the flux array.

In [34]:
conc_gradient = np.gradient(c, d)
print(conc_gradient)

flux_gradient = conc_gradient * -D

print(flux_gradient)

[-75. -70. -60. -55. -55.]
[1.575e-07 1.470e-07 1.260e-07 1.155e-07 1.155e-07]
